# Create this file: migrations/versions/add_p12_model_recommendations.py
# Or run: flask db migrate -m "Add model recommendations to P12 scenarios"

"""Add model recommendations to P12 scenarios

Revision ID: [auto-generated]
Revises: [previous migration id]
Create Date: [auto-generated]

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '[auto-generated]'
down_revision = '[previous_migration_id]'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('p12_scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('models_to_activate', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('models_to_avoid', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('risk_guidance', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_timeframes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('key_considerations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('p12_scenario', schema=None) as batch_op:
        batch_op.drop_column('key_considerations')
        batch_op.drop_column('preferred_timeframes')
        batch_op.drop_column('risk_guidance')
        batch_op.drop_column('models_to_avoid')
        batch_op.drop_column('models_to_activate')
    # ### end Alembic commands ###