"""Add full details to Instrument model

Revision ID: ae25eb922218
Revises: e0b083a82e25
Create Date: 2025-06-16 13:41:16.537573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae25eb922218'
down_revision = 'e0b083a82e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_journal', schema=None) as batch_op:
        batch_op.drop_column('wg_ny2_sf_lod_pct_h')
        batch_op.drop_column('wg_ny2_lf_hod_pct_l')
        batch_op.drop_column('wg_ny2_lt_lod_te')
        batch_op.drop_column('wg_ny2_sf_notes')
        batch_op.drop_column('wg_ny1_st_hod_ts')
        batch_op.drop_column('wg_ny2_st_hod_pct_l')
        batch_op.drop_column('wg_ny1_sf_lod_pct_h')
        batch_op.drop_column('wg_ny1_st_notes')
        batch_op.drop_column('wg_ny1_sf_hod_pct_h')
        batch_op.drop_column('wg_ny1_lf_hod_te')
        batch_op.drop_column('wg_ny2_sf_hod_pct_l')
        batch_op.drop_column('wg_ny1_lt_lod_te')
        batch_op.drop_column('wg_ny1_lt_lod_pct_l')
        batch_op.drop_column('wg_ny1_lf_lod_pct_h')
        batch_op.drop_column('wg_ny2_sf_lod_pct_l')
        batch_op.drop_column('wg_ny2_lt_lod_pct_l')
        batch_op.drop_column('wg_ny2_sf_hod_pct_h')
        batch_op.drop_column('wg_ny1_lt_lod_pct_h')
        batch_op.drop_column('wg_ny2_lt_hod_pct_h')
        batch_op.drop_column('wg_ny2_lt_lod_pct_h')
        batch_op.drop_column('wg_ny2_st_hod_te')
        batch_op.drop_column('wg_ny2_st_lod_pct_h')
        batch_op.drop_column('wg_ny1_st_lod_te')
        batch_op.drop_column('wg_ny2_lt_lod_ts')
        batch_op.drop_column('wg_ny2_sf_lod_te')
        batch_op.drop_column('wg_ny1_st_lod_ts')
        batch_op.drop_column('wg_ny1_st_lod_pct_h')
        batch_op.drop_column('wg_ny2_sf_lod_ts')
        batch_op.drop_column('wg_ny2_lf_notes')
        batch_op.drop_column('wg_ny2_lt_notes')
        batch_op.drop_column('wg_ny1_sf_lod_te')
        batch_op.drop_column('wg_ny1_st_hod_pct_l')
        batch_op.drop_column('wg_ny1_lf_lod_ts')
        batch_op.drop_column('wg_ny1_st_lod_pct_l')
        batch_op.drop_column('wg_ny1_lf_lod_pct_l')
        batch_op.drop_column('wg_ny1_lf_hod_ts')
        batch_op.drop_column('wg_ny2_lf_lod_ts')
        batch_op.drop_column('wg_ny2_lf_hod_ts')
        batch_op.drop_column('wg_ny2_st_hod_pct_h')
        batch_op.drop_column('wg_ny2_lf_lod_pct_l')
        batch_op.drop_column('wg_ny1_sf_lod_pct_l')
        batch_op.drop_column('wg_ny2_st_lod_te')
        batch_op.drop_column('wg_ny1_lf_lod_te')
        batch_op.drop_column('wg_ny2_sf_hod_ts')
        batch_op.drop_column('wg_ny1_lf_notes')
        batch_op.drop_column('wg_ny2_st_hod_ts')
        batch_op.drop_column('wg_ny1_st_hod_pct_h')
        batch_op.drop_column('wg_ny2_lt_hod_ts')
        batch_op.drop_column('wg_ny2_sf_hod_te')
        batch_op.drop_column('wg_ny1_sf_hod_te')
        batch_op.drop_column('wg_ny1_st_hod_te')
        batch_op.drop_column('wg_ny1_lt_lod_ts')
        batch_op.drop_column('wg_ny1_sf_notes')
        batch_op.drop_column('wg_ny2_lf_lod_te')
        batch_op.drop_column('wg_ny2_lf_hod_pct_h')
        batch_op.drop_column('wg_ny2_st_lod_pct_l')
        batch_op.drop_column('wg_ny2_lt_hod_te')
        batch_op.drop_column('wg_ny2_lt_hod_pct_l')
        batch_op.drop_column('wg_ny1_sf_hod_ts')
        batch_op.drop_column('wg_ny1_lf_hod_pct_h')
        batch_op.drop_column('wg_ny2_st_notes')
        batch_op.drop_column('wg_ny2_lf_lod_pct_h')
        batch_op.drop_column('wg_ny1_lf_hod_pct_l')
        batch_op.drop_column('wg_ny2_lf_hod_te')
        batch_op.drop_column('wg_ny2_st_lod_ts')
        batch_op.drop_column('wg_ny1_sf_lod_ts')
        batch_op.drop_column('wg_ny1_sf_hod_pct_l')

    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.alter_column('exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('asset_class',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('product_group',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_instrument_asset_class'), ['asset_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_instrument_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('point_value',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('point_value',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrument_is_active'))
        batch_op.drop_index(batch_op.f('ix_instrument_asset_class'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
        batch_op.alter_column('product_group',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('asset_class',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('daily_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wg_ny1_sf_hod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_sf_lod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_st_lod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lf_hod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lf_hod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lf_lod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_st_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lf_hod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_sf_hod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lt_hod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lt_hod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_st_lod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lf_hod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lf_lod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_sf_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lt_lod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_st_hod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_sf_hod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_sf_hod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lt_hod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_st_hod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_st_hod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lf_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_sf_hod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lf_lod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_st_lod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_sf_lod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lf_lod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_st_hod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lf_hod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lf_lod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lf_hod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lf_lod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_st_lod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lf_lod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_st_hod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_sf_lod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lt_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lf_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_sf_lod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_st_lod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_st_lod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_sf_lod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lt_lod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_st_lod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_st_lod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_st_hod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lt_lod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lt_hod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lt_lod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_sf_hod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lt_lod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_sf_lod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lf_lod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lt_lod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lt_lod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_sf_hod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_lf_hod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_sf_hod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_st_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_sf_lod_pct_h', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_st_hod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny1_st_hod_ts', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_sf_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lt_lod_te', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_lf_hod_pct_l', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wg_ny2_sf_lod_pct_h', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
