"""Add P12 scenarios

Revision ID: e4f518ed7f1e
Revises: 
Create Date: 2025-07-01 14:02:33.444166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f518ed7f1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p12_scenario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p12_high', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('p12_mid', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('p12_low', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('p12_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_dailyjournal_p12_scenario', 'p12_scenario', ['p12_scenario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_journal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dailyjournal_p12_scenario', type_='foreignkey')
        batch_op.drop_column('p12_notes')
        batch_op.drop_column('p12_low')
        batch_op.drop_column('p12_mid')
        batch_op.drop_column('p12_high')
        batch_op.drop_column('p12_scenario_id')

    # ### end Alembic commands ###
