"""Add pnl column to trades table

Revision ID: 0ee5b3d14ef5
Revises: fix_tag_unique_constraint_sqlite
Create Date: 2025-06-30 20:52:00.586270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee5b3d14ef5'
down_revision = 'fix_tag_unique_constraint_sqlite'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_new')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('performance_rating')

    with op.batch_alter_table('tag_usage_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tag_usage_last_used'))
        batch_op.drop_index(batch_op.f('idx_tag_usage_user_count'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_usage_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tag_usage_user_count'), ['user_id', 'usage_count'], unique=False)
        batch_op.create_index(batch_op.f('idx_tag_usage_last_used'), ['last_used'], unique=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance_rating', sa.VARCHAR(length=10), server_default=sa.text("'INFO'"), nullable=False))

    op.create_table('tag_new',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=23), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('color_category', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_tag_user')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name=op.f('uq_tag_name_user'))
    )
    # ### end Alembic commands ###
