"""Add user default tags relationship

Revision ID: 1884c589f6fd
Revises: add_tag_categories_simple
Create Date: 2025-06-19 13:22:59.664852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1884c589f6fd'
down_revision = 'add_tag_categories_simple'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_default_tags',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SETUP_STRATEGY', 'MARKET_CONDITIONS', 'EXECUTION_MANAGEMENT', 'PSYCHOLOGICAL_EMOTIONAL', name='tagcategory'),
               existing_nullable=False)
        batch_op.create_index('idx_tag_default_active', ['is_default', 'is_active'], unique=False)
        batch_op.create_index('idx_tag_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_unique_constraint('uq_tag_name_user', ['name', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tag_name_user', type_='unique')
        batch_op.drop_index('idx_tag_user_category')
        batch_op.drop_index('idx_tag_default_active')
        batch_op.alter_column('category',
               existing_type=sa.Enum('SETUP_STRATEGY', 'MARKET_CONDITIONS', 'EXECUTION_MANAGEMENT', 'PSYCHOLOGICAL_EMOTIONAL', name='tagcategory'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.drop_table('user_default_tags')
    # ### end Alembic commands ###
