"""Actually add pnl column to trade table

Revision ID: 3273ad4c23d1
Revises: 0ee5b3d14ef5
Create Date: 2025-06-30 20:58:54.572842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3273ad4c23d1'
down_revision = '0ee5b3d14ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pnl', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_trade_pnl'), ['pnl'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_pnl'))
        batch_op.drop_column('pnl')

    # ### end Alembic commands ###
