"""Add instrument table

Revision ID: e0b083a82e25
Revises: 4c2f55a637ba
Create Date: 2025-06-15 23:27:51.129696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b083a82e25'
down_revision = '4c2f55a637ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instrument_legacy', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_trade_instrument_legacy'), ['instrument_legacy'], unique=False)
        batch_op.create_foreign_key('fk_trade_instrument', 'instrument', ['instrument_id'], ['id'])
        batch_op.drop_column('instrument')
        batch_op.drop_column('point_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_value', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('instrument', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint('fk_trade_instrument', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trade_instrument_legacy'))
        batch_op.drop_column('instrument_legacy')
        batch_op.drop_column('instrument_id')

    # ### end Alembic commands ###
